FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]

RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list && \
    apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y zip bison build-essential cmake flex git curl libedit-dev wget \
    libllvm12 llvm-12-dev libclang-12-dev python3 python3-setuptools zlib1g-dev libelf-dev libfl-dev gnupg lsb-release\
    bpfcc-tools libelf-dev libpcap-dev gcc-multilib build-essential iputils-ping \
    liblzma-dev arping netperf iperf luajit libluajit-5.1-dev kmod tcpdump net-tools && \
    ln -sf /usr/bin/llc-12 /usr/bin/llc && \
    export LLVM_ROOT="/usr/lib/llvm-12" && \

    curl -s https://deb.frrouting.org/frr/keys.asc | apt-key add - && \
    echo deb https://deb.frrouting.org/frr $(lsb_release -sc) frr-stable | tee -a /etc/apt/sources.list.d/frr.list && \
    apt update && \
    apt install -y frr frr-pythontools && \

    wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz && \
    rm go1.21.0.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"


RUN go env -w GOPROXY=https://goproxy.cn,direct

WORKDIR /app
COPY ../controller/server/go.mod ../controller/server/go.sum /app/controller/server/
RUN cd /app/controller/server && \
    go mod download && \
    go mod tidy && \
    sed -i 's/bgpd=no/bgpd=yes/g' /etc/frr/daemons && \
    sed -i 's/ospfd=no/ospfd=yes/g' /etc/frr/daemons && \
    sed -i 's/ospf6d=no/ospf6d=yes/g' /etc/frr/daemons && \
    sed -i 's/isisd=no/isisd=yes/g' /etc/frr/daemons && \
    sed -i 's/bfdd=no/bfdd=yes/g' /etc/frr/daemons && \
    sed -i 's/pathd=no/pathd=yes/g' /etc/frr/daemons

COPY ../controller /app/controller
RUN cd /app/controller/server && \
    rm -rf server && \
    go build -o server server.go
    
EXPOSE 50051

CMD ["./controller/server/server"]
