// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.2
// source: proto/controller.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 探测任务请求消息结构
type AgentGetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentInfo     string                 `protobuf:"bytes,1,opt,name=AgentInfo,proto3" json:"AgentInfo,omitempty"` // 探针信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentGetTaskRequest) Reset() {
	*x = AgentGetTaskRequest{}
	mi := &file_proto_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentGetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGetTaskRequest) ProtoMessage() {}

func (x *AgentGetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGetTaskRequest.ProtoReflect.Descriptor instead.
func (*AgentGetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{0}
}

func (x *AgentGetTaskRequest) GetAgentInfo() string {
	if x != nil {
		return x.AgentInfo
	}
	return ""
}

// 探测任务下发消息结构
type ControllerTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"` // 任务的 JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerTaskReply) Reset() {
	*x = ControllerTaskReply{}
	mi := &file_proto_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerTaskReply) ProtoMessage() {}

func (x *ControllerTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerTaskReply.ProtoReflect.Descriptor instead.
func (*ControllerTaskReply) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerTaskReply) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

// Agent报告上报请求消息结构
type AgentUploadReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        string                 `protobuf:"bytes,1,opt,name=Report,proto3" json:"Report,omitempty"` // 探针上报的状态信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUploadReportRequest) Reset() {
	*x = AgentUploadReportRequest{}
	mi := &file_proto_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUploadReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUploadReportRequest) ProtoMessage() {}

func (x *AgentUploadReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUploadReportRequest.ProtoReflect.Descriptor instead.
func (*AgentUploadReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{2}
}

func (x *AgentUploadReportRequest) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

// Controller响应消息结构
type ControllerResponseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resonse       string                 `protobuf:"bytes,1,opt,name=Resonse,proto3" json:"Resonse,omitempty"` // 响应结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerResponseReply) Reset() {
	*x = ControllerResponseReply{}
	mi := &file_proto_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerResponseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerResponseReply) ProtoMessage() {}

func (x *ControllerResponseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerResponseReply.ProtoReflect.Descriptor instead.
func (*ControllerResponseReply) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{3}
}

func (x *ControllerResponseReply) GetResonse() string {
	if x != nil {
		return x.Resonse
	}
	return ""
}

// Agent数据上报请求消息结构
type AgentUploadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"` // 探针上报的数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUploadDataRequest) Reset() {
	*x = AgentUploadDataRequest{}
	mi := &file_proto_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUploadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUploadDataRequest) ProtoMessage() {}

func (x *AgentUploadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUploadDataRequest.ProtoReflect.Descriptor instead.
func (*AgentUploadDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{4}
}

func (x *AgentUploadDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_proto_controller_proto protoreflect.FileDescriptor

const file_proto_controller_proto_rawDesc = "" +
	"\n" +
	"\x16proto/controller.proto\x12\n" +
	"Controller\"3\n" +
	"\x13AgentGetTaskRequest\x12\x1c\n" +
	"\tAgentInfo\x18\x01 \x01(\tR\tAgentInfo\")\n" +
	"\x13ControllerTaskReply\x12\x12\n" +
	"\x04Task\x18\x01 \x01(\tR\x04Task\"2\n" +
	"\x18AgentUploadReportRequest\x12\x16\n" +
	"\x06Report\x18\x01 \x01(\tR\x06Report\"3\n" +
	"\x17ControllerResponseReply\x12\x18\n" +
	"\aResonse\x18\x01 \x01(\tR\aResonse\",\n" +
	"\x16AgentUploadDataRequest\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data2l\n" +
	"\x10TaskDistribution\x12X\n" +
	"\x14GetProbeDestinations\x12\x1f.Controller.AgentGetTaskRequest\x1a\x1f.Controller.ControllerTaskReply2m\n" +
	"\vProbeStatus\x12^\n" +
	"\x11ReportProbeStatus\x12$.Controller.AgentUploadReportRequest\x1a#.Controller.ControllerResponseReply2g\n" +
	"\tProbeData\x12Z\n" +
	"\x0fReportProbeData\x12\".Controller.AgentUploadDataRequest\x1a#.Controller.ControllerResponseReplyB\x0fZ\r./proto_go;pbb\x06proto3"

var (
	file_proto_controller_proto_rawDescOnce sync.Once
	file_proto_controller_proto_rawDescData []byte
)

func file_proto_controller_proto_rawDescGZIP() []byte {
	file_proto_controller_proto_rawDescOnce.Do(func() {
		file_proto_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controller_proto_rawDesc), len(file_proto_controller_proto_rawDesc)))
	})
	return file_proto_controller_proto_rawDescData
}

var file_proto_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_controller_proto_goTypes = []any{
	(*AgentGetTaskRequest)(nil),      // 0: Controller.AgentGetTaskRequest
	(*ControllerTaskReply)(nil),      // 1: Controller.ControllerTaskReply
	(*AgentUploadReportRequest)(nil), // 2: Controller.AgentUploadReportRequest
	(*ControllerResponseReply)(nil),  // 3: Controller.ControllerResponseReply
	(*AgentUploadDataRequest)(nil),   // 4: Controller.AgentUploadDataRequest
}
var file_proto_controller_proto_depIdxs = []int32{
	0, // 0: Controller.TaskDistribution.GetProbeDestinations:input_type -> Controller.AgentGetTaskRequest
	2, // 1: Controller.ProbeStatus.ReportProbeStatus:input_type -> Controller.AgentUploadReportRequest
	4, // 2: Controller.ProbeData.ReportProbeData:input_type -> Controller.AgentUploadDataRequest
	1, // 3: Controller.TaskDistribution.GetProbeDestinations:output_type -> Controller.ControllerTaskReply
	3, // 4: Controller.ProbeStatus.ReportProbeStatus:output_type -> Controller.ControllerResponseReply
	3, // 5: Controller.ProbeData.ReportProbeData:output_type -> Controller.ControllerResponseReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_controller_proto_init() }
func file_proto_controller_proto_init() {
	if File_proto_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controller_proto_rawDesc), len(file_proto_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_controller_proto_goTypes,
		DependencyIndexes: file_proto_controller_proto_depIdxs,
		MessageInfos:      file_proto_controller_proto_msgTypes,
	}.Build()
	File_proto_controller_proto = out.File
	file_proto_controller_proto_goTypes = nil
	file_proto_controller_proto_depIdxs = nil
}
